# Generated by Django 4.0.3 on 2022-10-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COACH', 'Coach'), ('CLIENT', 'Client')], default='CLIENT', max_length=50),
        ),
    ]
