# Generated by Django 4.0.3 on 2022-11-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingProgram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='date_creted',
        ),
        migrations.AddField(
            model_name='program',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
